// The wire types come from pkg/apis/compute/types.go via tygo
// (ui/src/generated/compute.ts, committed and regenerated by `make
// generate`). Re-exported here so pages import from one module-local
// place, and so a frontend-only shape has somewhere to live that is not
// the generated file.
//
// AgentStatus deserves a note the generator cannot carry: it is
// "online", "offline", or ABSENT. Absent is not a missing value -- it is
// the state a host imported by hand sits in until someone installs an
// agent, and the list renders it as "not installed". Treating it as
// offline erases the difference between a host waiting for an install
// and one whose machine has stopped answering.
export type { Host, HostSpec, AgentJoinToken, AgentJoinTokenSpec } from "@/generated/compute"

import type { Host, AgentJoinToken } from "@/generated/compute"
import type { ListResponse } from "@/core/api/resource-api"

export type HostList = ListResponse<Host>
export type AgentJoinTokenList = ListResponse<AgentJoinToken>
