package hostinfo

import (
	"reflect"
	"strings"
	"testing"

	agenttypes "vraxel.io/vraxel/lib/agent/types"
)

func TestParsePasswd(t *testing.T) {
	const passwd = `root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
zly:x:1000:1000:zly,,,:/home/zly:/bin/bash
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
broken:x:notanumber:5::/tmp:/bin/sh
# a comment
`
	got := parsePasswd([]byte(passwd))
	if len(got) != 4 {
		t.Fatalf("got %d entries %+v, want 4", len(got), got)
	}
	if got[2].name != "zly" || got[2].uid != 1000 || got[2].home != "/home/zly" {
		t.Errorf("zly = %+v", got[2])
	}
}

// A uid is an unsigned 32-bit value, and the conventional "nobody" on
// several systems is 4294967294. In an int32 field that is a negative
// user id.
func TestParsePasswdHighUID(t *testing.T) {
	got := parsePasswd([]byte("nobody:x:4294967294:4294967294::/:/sbin/nologin\n"))
	if len(got) != 1 || got[0].uid != 4294967294 {
		t.Fatalf("got %+v, want uid 4294967294", got)
	}
}

func TestPasswordState(t *testing.T) {
	for field, want := range map[string]string{
		"$6$abc$def": agenttypes.PwSet,
		"!$6$abc$de": agenttypes.PwLocked,
		"!!":         agenttypes.PwLocked,
		"!":          agenttypes.PwLocked,
		"*":          agenttypes.PwDisabled,
		"x":          agenttypes.PwDisabled,
		// The one value here that is a finding: no password REQUIRED, not
		// "no password set".
		"": agenttypes.PwEmpty,
	} {
		if got := passwordState(field); got != want {
			t.Errorf("passwordState(%q) = %q, want %q", field, got, want)
		}
	}
}

func TestCanLogin(t *testing.T) {
	for shell, want := range map[string]bool{
		"/bin/bash":         true,
		"/bin/sh":           true,
		"/usr/bin/zsh":      true,
		"/usr/sbin/nologin": false,
		"/sbin/nologin":     false,
		"/bin/false":        false,
		"/bin/sync":         false,
		// No shell listed is not a refusal: the kernel falls back to
		// /bin/sh, so this account has one.
		"": true,
	} {
		if got := canLogin(shell); got != want {
			t.Errorf("canLogin(%q) = %v, want %v", shell, got, want)
		}
	}
}

// The regression that made root look like it had no sudo rule: the distro
// default is TAB separated and its first SPACE falls inside the runas
// list, so splitting on the first space yields "root\tALL=(ALL:ALL)".
func TestSudoersRuleWho(t *testing.T) {
	for line, want := range map[string][]string{
		"root\tALL=(ALL:ALL) ALL":        {"root"},
		"%sudo\tALL=(ALL:ALL) ALL":       {"%sudo"},
		"%wheel ALL=(ALL) NOPASSWD: ALL": {"%wheel"},
		// The who part is a list, and a list is allowed spaces after its
		// commas.
		"alice, bob ALL=(ALL) ALL":                           {"alice", "bob"},
		"deploy ALL = (root) /usr/bin/systemctl restart app": {"deploy"},
		"ADMINS ALL=(ALL) ALL":                               {"ADMINS"},
		// Not a rule.
		"Defaults env_reset": nil,
		"nonsense":           nil,
	} {
		if got := sudoersRuleWho(line); !reflect.DeepEqual(got, want) {
			t.Errorf("sudoersRuleWho(%q) = %q, want %q", line, got, want)
		}
	}
}

func TestParseSudoers(t *testing.T) {
	files := map[string][]byte{
		"/etc/sudoers": []byte(`# comment
Defaults	env_reset
root	ALL=(ALL:ALL) ALL
%sudo	ALL=(ALL:ALL) ALL
#includedir /etc/sudoers.d
`),
		// An alias defined in an included file and used in it: sudo
		// resolves aliases across the whole set, so a single pass in file
		// order would miss a rule that precedes its own alias.
		"/etc/sudoers.d/team": []byte(`ADMINS	ALL=(ALL) ALL
User_Alias ADMINS = alice, bob
`),
	}
	order := []string{"/etc/sudoers", "/etc/sudoers.d/team"}
	rules, who := parseSudoers(files, order)

	// Defaults, comments and the include directive are configuration, not
	// grants, and none of them belong in front of an operator asking who
	// can become root.
	if len(rules) != 3 {
		t.Errorf("rules = %q, want 3 grant lines", rules)
	}
	for _, u := range []string{"root", "alice", "bob"} {
		if _, ok := who.users[u]; !ok {
			t.Errorf("user %q not recognised, users = %v", u, who.users)
		}
	}
	if _, ok := who.groups["sudo"]; !ok {
		t.Errorf("group sudo not recognised, groups = %v", who.groups)
	}
	// The alias name is not itself an account.
	if _, ok := who.users["ADMINS"]; ok {
		t.Error("User_Alias name leaked into the user set")
	}
}

func TestSudoersIncludes(t *testing.T) {
	// "#includedir" is a comment everywhere else in Unix, which is exactly
	// why a naive comment filter drops sudo's include directive.
	got := sudoersIncludes([]byte("# real comment\n#includedir /etc/sudoers.d\n@includedir /opt/sudoers.d\n"))
	want := []string{"/etc/sudoers.d", "/opt/sudoers.d"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestParseAuthorizedKeys(t *testing.T) {
	// Real keys with their real fingerprints, generated by ssh-keygen and
	// pasted in. A hand-written blob is not a shortcut here: base64 that
	// does not decode silently yields no keys at all, which is exactly how
	// this test first passed on an empty result.
	const keys = `# a comment

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDbOg5aSTHiUXsGe6RGI5SrhDt5PNkg2SN7XTLIsMmzg zly@laptop
command="/usr/bin/backup",no-pty ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDfiHMaG8SxDs094iVU90qbRzkSimlMQy4ncc5O4xwtauTm0InPX4OiiS0fmtP5zVs1eGKaRcEYAJ9rI3MPxbSuY4UE1B7HpVk6a393XXfQ55ip0GWV2dL9yuwfEzDuEQGT02uocE+kQghv0Yxd6qjWclNmSjzkHTDAKnZMcZpzeIfgnGuAQLYjKFzCq9mPVu6cvvXOwsWuNhvTYqRP63wptmG/FDvGMfK0IR3jSP30KKbMveA4dUa1jr3VVCdEq1rTkMYBpgzuZdqS4bbP7T5K4gtex1++rRcknntBvKHNyTfPo+IeZAey9J3eLn9O18WXLJ2KRxJjNqtg/XjRI2x backup key
not-a-key-line at all
`
	got := parseAuthorizedKeys([]byte(keys))
	if len(got) != 2 {
		t.Fatalf("got %d keys %+v, want 2", len(got), got)
	}
	if got[0].Type != "ssh-ed25519" || got[0].Comment != "zly@laptop" {
		t.Errorf("key 0 = %+v", got[0])
	}
	if got[0].Fingerprint != "SHA256:GXwr1LxBshWPnM9DJRZAEeVEvB9zXXlKN1ydp+AATPs" {
		t.Errorf("ed25519 fingerprint = %q, want %q", got[0].Fingerprint, "SHA256:GXwr1LxBshWPnM9DJRZAEeVEvB9zXXlKN1ydp+AATPs")
	}
	// An options list precedes the type and contains spaces of its own, so
	// field 0 is not the algorithm.
	if got[1].Type != "ssh-rsa" || got[1].Comment != "backup key" {
		t.Errorf("key 1 = %+v", got[1])
	}
	if got[1].Fingerprint != "SHA256:m4qqusdy6Jyu1XSQb/OjHlliQwUKydbdNC3cpf/ORgk" {
		t.Errorf("rsa fingerprint = %q, want %q", got[1].Fingerprint, "SHA256:m4qqusdy6Jyu1XSQb/OjHlliQwUKydbdNC3cpf/ORgk")
	}
}

// The value ssh-keygen -l prints for this exact key. Computed in Go
// rather than shelled out, so it has to agree with OpenSSH byte for byte
// or the fingerprints in the UI are ones nobody can match against
// anything.
func TestSSHFingerprintMatchesOpenSSH(t *testing.T) {
	got, ok := sshFingerprint("AAAAC3NzaC1lZDI1NTE5AAAAIDbOg5aSTHiUXsGe6RGI5SrhDt5PNkg2SN7XTLIsMmzg")
	if !ok {
		t.Fatal("fingerprint failed on a valid key")
	}
	if got != "SHA256:GXwr1LxBshWPnM9DJRZAEeVEvB9zXXlKN1ydp+AATPs" {
		t.Errorf("got %q, want %q", got, "SHA256:GXwr1LxBshWPnM9DJRZAEeVEvB9zXXlKN1ydp+AATPs")
	}
	// Not base64 at all: no key, not a fingerprint of the garbage.
	if _, ok := sshFingerprint("!!!not base64!!!"); ok {
		t.Error("accepted a blob that is not base64")
	}
}

func TestPrivilegesOf(t *testing.T) {
	who := sudoersWho{
		users:  map[string]struct{}{"deploy": {}},
		groups: map[string]struct{}{"sudo": {}},
	}
	for _, tc := range []struct {
		name string
		acct agenttypes.Account
		want []string
	}{
		{"uid 0", agenttypes.Account{Name: "root", UID: 0}, []string{agenttypes.PrivRoot}},
		{"a second uid 0 is still root", agenttypes.Account{Name: "backdoor", UID: 0}, []string{agenttypes.PrivRoot}},
		{"named by a rule", agenttypes.Account{Name: "deploy", UID: 1001}, []string{agenttypes.PrivSudo}},
		{"in a group a rule names", agenttypes.Account{Name: "amy", UID: 1002, Groups: []string{"sudo"}}, []string{agenttypes.PrivSudo}},
		// Root by a route that appears nowhere in sudoers: a member can
		// bind-mount the host root into a container and write to it.
		{"docker group", agenttypes.Account{Name: "ci", UID: 1003, Groups: []string{"docker"}}, []string{agenttypes.PrivDockerGroup}},
		// /etc/group holds only SUPPLEMENTARY members, so an account whose
		// PRIMARY group is docker is invisible there while being just as
		// privileged.
		{"docker as primary group", agenttypes.Account{Name: "svc", UID: 1004, Group: "docker"}, []string{agenttypes.PrivDockerGroup}},
		{"ordinary", agenttypes.Account{Name: "zly", UID: 1000, Groups: []string{"audio", "video"}}, nil},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := privilegesOf(tc.acct, who); !reflect.DeepEqual(got, tc.want) {
				t.Errorf("got %q, want %q", got, tc.want)
			}
		})
	}
}

func TestBuildAccountsResolvesGroups(t *testing.T) {
	users := []passwdEntry{
		{name: "root", uid: 0, gid: 0, home: "/root", shell: "/bin/bash"},
		{name: "zly", uid: 1000, gid: 1000, home: "/home/zly", shell: "/bin/bash"},
	}
	groups := []agenttypes.UserGroup{
		{Name: "root", GID: 0},
		{Name: "sudo", GID: 27, Members: []string{"zly"}},
		{Name: "zly", GID: 1000},
	}
	shadow := map[string]shadowEntry{
		"root": {state: agenttypes.PwLocked, changedDays: -1, expireDays: -1},
		// 20336 days after the epoch is 2025-09-12; expiry left blank.
		"zly": {state: agenttypes.PwSet, changedDays: 20336, expireDays: -1},
	}
	who := sudoersWho{users: map[string]struct{}{}, groups: map[string]struct{}{"sudo": {}}}

	accounts, _ := buildAccounts(users, groups, shadow, who, nil, nil)
	if len(accounts) != 2 {
		t.Fatalf("got %d accounts", len(accounts))
	}
	zly := accounts[1]
	if zly.Group != "zly" {
		t.Errorf("primary group = %q, want zly", zly.Group)
	}
	if !reflect.DeepEqual(zly.Groups, []string{"sudo"}) {
		t.Errorf("supplementary groups = %q", zly.Groups)
	}
	if !reflect.DeepEqual(zly.Privileges, []string{agenttypes.PrivSudo}) {
		t.Errorf("privileges = %q, want sudo via group membership", zly.Privileges)
	}
	if accounts[0].Password != agenttypes.PwLocked {
		t.Errorf("root password state = %q", accounts[0].Password)
	}
	if zly.PasswordChangedAtMs != 20336*86400*1000 {
		t.Errorf("password change date = %d", zly.PasswordChangedAtMs)
	}
	// A blank expiry is absent, not the epoch -- an account showing
	// "expired 1970-01-01" is a false finding on every ordinary machine.
	if zly.ExpiresAtMs != 0 || accounts[0].PasswordChangedAtMs != 0 {
		t.Errorf("a blank shadow counter became a date: %+v", zly)
	}
}

func TestShadowDays(t *testing.T) {
	for in, want := range map[string]int64{
		"20336": 20336,
		// Not blank: in the lastchg column 0 means "must change at next
		// login", which is exactly the freshly-provisioned account
		// somebody wants to find.
		"0":  0,
		"":   -1,
		" ":  -1,
		"-1": -1,
		"xx": -1,
	} {
		if got := shadowDays(in); got != want {
			t.Errorf("shadowDays(%q) = %d, want %d", in, got, want)
		}
	}
	if daysToUnixMs(-1) != 0 {
		t.Error("an absent counter must not become a date")
	}
}

func TestGecosName(t *testing.T) {
	for in, want := range map[string]string{
		// The passwd comment is a 1970s campus directory record; only the
		// first field was ever a name.
		"zly,,,":                     "zly",
		"Zhou Leyan,Room 5,555-1234": "Zhou Leyan",
		" Padded Name , x":           "Padded Name",
		"":                           "",
		",,,":                        "",
	} {
		if got := gecosName(in); got != want {
			t.Errorf("gecosName(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestParseShadowKeepsNoHash(t *testing.T) {
	const shadow = `root:$6$saltsalt$averylonghashthatmustnevertravel:20336:0:99999:7:::
svc:!:19000:0:99999:7:::
tmp::20000:0:99999:7::20400:
`
	got := parseShadow([]byte(shadow))
	if got["root"].state != agenttypes.PwSet || got["root"].changedDays != 20336 {
		t.Errorf("root = %+v", got["root"])
	}
	if got["svc"].state != agenttypes.PwLocked {
		t.Errorf("svc = %+v", got["svc"])
	}
	if got["tmp"].state != agenttypes.PwEmpty || got["tmp"].expireDays != 20400 {
		t.Errorf("tmp = %+v", got["tmp"])
	}
	// The one invariant that matters: nothing in the returned structure
	// can be used to authenticate as anybody.
	for name, e := range got {
		if strings.Contains(e.state, "$") {
			t.Fatalf("a hash survived into %s: %+v", name, e)
		}
	}
}
